apiVersion: apps/v1
kind: Deployment
metadata:
  name: power-reporter
spec:
  selector:
    matchLabels:
      app: power-reporter
  template:
    metadata:
      labels:
        app: power-reporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/"
    spec:
      containers:
        - name: power-reporter
          image: srvu:5000/power-reporter:${IMAGE_TAG}
          imagePullPolicy: Always
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "500m"
          ports:
            - containerPort: 9102
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 9102
          #   initialDelaySeconds: 2
          #   periodSeconds: 3
